name: Feature Request
description: Suggest a new feature for Forensicate.ai
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Web App
        - Chrome/Firefox Extension
        - Scanner Engine (new rules)
        - API
        - VS Code Extension
        - Other
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?
